services:
  - type: web
    name: nantwich-town-fc-dabbers-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
    autoDeploy: true
